from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
TOOLS_DIR = ROOT_DIR / "tools"
SKILLS_DIR = ROOT_DIR / "skills"
MEMORY_DIR = ROOT_DIR / "memory"
CONFIG_DIR = ROOT_DIR / "config"
LLM_CONFIG_DIR = CONFIG_DIR / "llm"
TOOLS_CONFIG_DIR = CONFIG_DIR / "tools"
SKILLS_CONFIG_DIR = CONFIG_DIR / "skills"
SYSTEM_CONFIG_DIR = CONFIG_DIR / "system"
LOGS_DIR = ROOT_DIR / "logs"
PROMPTS_DIR = ROOT_DIR / "prompts"
PROPOSALS_DIR = ROOT_DIR / "proposals"
USER_KNOWLEDGE_DIR = ROOT_DIR / "user_knowledge"

TOOL_REGISTRY_FILE = TOOLS_CONFIG_DIR / "tool_registry.json"
SKILL_REGISTRY_FILE = SKILLS_CONFIG_DIR / "skill_registry.json"
LLM_CONFIG_FILE = LLM_CONFIG_DIR / "llm_config.json"
LLM_CONFIG_TEMPLATE_FILE = LLM_CONFIG_DIR / "llm_config.template.json"
LLM_CONFIG_LOCAL_FILE = LLM_CONFIG_DIR / "llm_config.local.json"
SYSTEM_CONFIG_FILE = SYSTEM_CONFIG_DIR / "pandora.json"
LEGACY_TOOL_REGISTRY_FILE = MEMORY_DIR / "tool_registry.json"
LEGACY_SKILL_REGISTRY_FILE = MEMORY_DIR / "skill_registry.json"
LEGACY_LLM_CONFIG_FILE = MEMORY_DIR / "llm_config.json"
LEGACY_LLM_CONFIG_TEMPLATE_FILE = MEMORY_DIR / "llm_config.template.json"
LEGACY_LLM_CONFIG_LOCAL_FILE = MEMORY_DIR / "llm_config.local.json"
ENV_FILE = ROOT_DIR / ".env"
AGENT_JOURNAL_FILE = MEMORY_DIR / "agent_journal.jsonl"
IMPROVEMENTS_DIR = PROPOSALS_DIR / "improvements"

PROTECTED_CORE_FILES = {
    "heartbeat.py", "rollback_manager.py", "recovery.py", "security.py",
    "activation_manager.py", "core_version_manager.py", "config.py",
}

GENERATED_TOOLS_DIR = ROOT_DIR / "generated_tools"
TOOL_PROPOSALS_DIR = ROOT_DIR / "tool_proposals"
TOOL_ACTIVATION_LOG = MEMORY_DIR / "tool_activation_log.jsonl"
TOOL_USAGE_STATS_FILE = MEMORY_DIR / "tool_usage_stats.json"
TOOL_LIFECYCLE_LOG_FILE = MEMORY_DIR / "tool_lifecycle_log.jsonl"

CAPABILITY_EVENT_LOG = MEMORY_DIR / "capability_events.jsonl"

CAPABILITY_WORKFLOW_LOG = MEMORY_DIR / "capability_workflow_log.jsonl"

SKILL_PROPOSALS_DIR = ROOT_DIR / "skill_proposals"
SKILL_ACTIVATION_LOG = MEMORY_DIR / "skill_activation_log.jsonl"
LEARNING_EVENTS_FILE = MEMORY_DIR / "learning_events.jsonl"
STRATEGY_MEMORY_FILE = MEMORY_DIR / "strategy_memory.json"
RANKINGS_FILE = MEMORY_DIR / "tool_skill_rankings.json"
FAILURE_ANALYSIS_FILE = MEMORY_DIR / "failure_analysis.json"
RECOMMENDATIONS_FILE = MEMORY_DIR / "recommendations.json"
DOCS_DIR = ROOT_DIR / "docs"
CHANGELOG_FILE = DOCS_DIR / "changelog.md"
GOVERNANCE_REPORT_FILE = MEMORY_DIR / "governance_report.json"
ARCHITECTURE_REPORT_FILE = MEMORY_DIR / "architecture_report.json"

SANDBOX_DIR = ROOT_DIR / "sandbox"
SANDBOX_RUNS_DIR = SANDBOX_DIR / "runs"
SANDBOX_TMP_DIR = SANDBOX_DIR / "tmp"
SANDBOX_LOG_FILE = MEMORY_DIR / "sandbox_log.jsonl"
EXECUTION_POLICY_FILE = TOOLS_CONFIG_DIR / "execution_policy.json"
LEGACY_EXECUTION_POLICY_FILE = MEMORY_DIR / "execution_policy.json"
TOOL_GENERATION_LOG_FILE = MEMORY_DIR / "tool_generation_log.jsonl"
TOOL_REPAIR_LOG_FILE = MEMORY_DIR / "tool_repair_log.jsonl"

CORE_VERSIONS_DIR = ROOT_DIR / "core_versions"
CORE_VERSION_INDEX_FILE = MEMORY_DIR / "core_versions.json"
CORE_STATUS_FILE = MEMORY_DIR / "core_status.json"
CORE_ROLLBACK_LOG_FILE = MEMORY_DIR / "core_rollback_log.jsonl"
REALITY_CHECK_LOG_FILE = MEMORY_DIR / "reality_check_log.jsonl"
STABILITY_REPORT_FILE = MEMORY_DIR / "stability_report.json"
PLANNER_AGENT_LOG_FILE = MEMORY_DIR / "planner_agent_log.jsonl"
TASK_PLANS_DIR = MEMORY_DIR / "task_plans"
WORKER_AGENT_LOG_FILE = MEMORY_DIR / "worker_agent_log.jsonl"
TASK_EXECUTIONS_DIR = MEMORY_DIR / "task_executions"
CHAT_SESSIONS_DIR = MEMORY_DIR / "chat_sessions"
CHAT_SESSION_INDEX_FILE = MEMORY_DIR / "chat_sessions.json"
CONVERSATION_MEMORY_FILE = MEMORY_DIR / "conversation_memory.json"
CONVERSATION_MEMORY_LOG_FILE = MEMORY_DIR / "conversation_memory_log.jsonl"
COORDINATOR_LOG_FILE = MEMORY_DIR / "coordinator_log.jsonl"
